### ISSUE TITLE
PNG imgaes not compressing

### ISSUE THREAD

**Issue by trymeouteh** [Huluti/ImCompressor#11]
I tried to compress this image and it does not do anything. I tested JPG images and they do compress.

I got the app from the AUR and I am on Manjaro

https://pngriver.com/wp-content/uploads/2017/11/watermelon-transparent-png-images-free-download-Watermelon-PNG-image-2-001.png

**Comment by Huluti** [comment]
If you have tried to open the image through your file manager, it should be fixed in 0.5.1.
I have tried your image and it works for me.

**Comment by trymeouteh** [comment]
I just updated it to 0.5.2 and it will not work weather I drag n drop it or click "Browser your files" and select the image.

**Comment by Huluti** [comment]
Could you try to open it in command line like this:

    imcompressor watermelon-transparent-png-images-free-download-Watermelon-PNG-image-2-001.png

and see if there is an error in the terminal.

**Comment by trymeouteh** [comment]
```
$ imcompressor "/home/alex/Downloads/watermelon-transparent-png-images-free-download-Watermelon-PNG-image-2-001.png"
Traceback (most recent call last):
  File "/usr/share/imcompressor/imcompressor/main.py", line 52, in file_open_handler
    self.win.handle_filenames(filenames)
  File "/usr/share/imcompressor/imcompressor/window.py", line 185, in handle_filenames
    self.compress_image(filename, new_filename)
  File "/usr/share/imcompressor/imcompressor/window.py", line 234, in compress_image
    compressor.compress_image()
  File "/usr/share/imcompressor/imcompressor/compressor.py", line 49, in compress_image
    ret = self.call_compressor(file_data['ext'])
  File "/usr/share/imcompressor/imcompressor/compressor.py", line 72, in call_compressor
    ret = subprocess.call(command)
  File "/usr/lib/python3.7/subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'optipng': 'optipng'
```

**Comment by Huluti** [comment]
optipng should be installed. the aur package do not specify it. Try to install optipng with:

    sudo pacman -S optipng

and retry. I'll let a comment on the AUR page to ask a modification of the package.

**Comment by yochananmarqos** [comment]
@trymeouteh Please update to v0.5.2-2, I added `optipng` as a dependency.

**Comment by Huluti** [comment]
@yochananmarqos thank you ;)

**Comment by Huluti** [comment]
Future errors like this one will be shown in a dialog now (https://github.com/Huluti/ImCompressor/commit/111cfe3b5a1ec33e112d69e9c78d0ee7a0ce2fbe). Thank's for your report ;)

**Comment by trymeouteh** [comment]
Fixed in new release, thank you!
