### ISSUE TITLE
Implement more compression options (lossless)

### ISSUE THREAD

**Issue by trymeouteh** [Huluti/ImCompressor#13]
FileOptimier which I use using WINE does a bit better of a job compressing PNG images, please add these PNG compression features into ImCompressor.

**Comment by Huluti** [comment]
Isn't it the same request as #6?

**Comment by trymeouteh** [comment]
I would like more loseless compression on PNG files, not lossy.

**Comment by Huluti** [comment]
Fixed in part with 0.6 with a new option. Please don't hesitate to open new issues for specific requests.

**Comment by trymeouteh** [comment]
Is it possible to add more loseless compression options for PNG files? I am comparing ImCompessor to FileOptimizer which is a great file compressor program for windows which works in Wine but I would always prefer to use a native linux application over using Windows apps in Wine.

ImCompressor JPG compression is the same as FileCompressor with the tests I have done with the same image. However FileOptimizer compression has a better loseless compression on PNG files especially for big images.

For example, when I compress the PNG file in the link below using ImCompressor it will become 1,194,081 bytes in size. With FileOptimizer it will become 951,995 bytes in size.

https://pngriver.com/wp-content/uploads/2018/04/Download-Electronic-Arts-PNG-Image.png

https://nikkhokkho.sourceforge.io/static.php?page=FileOptimizer
