### ISSUE TITLE
0.6 release 🚀

### ISSUE THREAD

**Issue by Huluti** [Huluti/ImCompressor#14]
HI! A new release will be out soon (no date yet) with some cool new features to fix #6 and #13:

### Added
- Add lossy compression features.
- Add options to change compression levels.
- New layout for the preferences dialog.

### Changed
- Don't permit higher resulting size.
- Better displaying of the drag area.
- Update translations.

### Fixed
- Catch errors in subprocess to avoid crashing the app.

In order to have a good release I need some help of the translators to update their translations and ideally, it would be nice if some people test the new version from the source code to detect possible bugs.

**TODO before 0.6 release:**
- [x] update translations
    - [x] de :@Etamuk
    - [x] nl: @Vistaus
    - [ ] it: @albanobattistella
- [x] test the soft

Screenshots: 
![Capture d’écran du 2019-10-17 23-29-16](https://user-images.githubusercontent.com/5782198/67049250-11c28700-f136-11e9-9a9f-1cdd4e15618e.png)
![Capture d’écran du 2019-10-17 23-29-43](https://user-images.githubusercontent.com/5782198/67049251-125b1d80-f136-11e9-9df6-09dcf98fc357.png)

Thank's in advance! 🚀

**Comment by Vistaus** [comment]
Done! And thanks for the heads-up so that I could update it *before* the release :-)

**Comment by Huluti** [comment]
@Etamuk @Vistaus I've just added two new strings to translate before 0.6 in f83e0b8b1bccf857ec6b7677a342218d675bcb90 (sorry...).

**Comment by Vistaus** [comment]
@Huluti No need to apologize! I translated them and sent a PR :[)

**Comment by Huluti** [comment]
I'll release 0.6 later today ;)

**Comment by Huluti** [comment]
0.6 released!

**Comment by Etamuk** [comment]
Very nice!
