### ISSUE TITLE
Feature Request: Keep Image Metadata

### ISSUE THREAD

**Issue by trymeouteh** [Huluti/ImCompressor#19]
Please add a option on the main page before you select your files on weather to keep or remove the image metadata. Metadata such as title, tags, geolocation, camera manufacture and so on.

I would prefer if the metadata was kept by default to prevent any mistakes, if a user compressed his images and made the mistake and forgot to enable the remove metadata switch, then they can do it again but if it was the other way around and they do not have the -min enabled then they would lose all the metadata.

This feature will make it handy for compressing my family photos which heavily rely on metadata without removing the metadata itself.

**Comment by Huluti** [comment]
Very good suggestion. I'll see what I can do.

**Comment by Huluti** [comment]
Fixed in master. A new option is available in the preferences window. Will be in 0.8.
