### ISSUE TITLE
Distribution: Provide more packaging options

### ISSUE THREAD

**Issue by gsantner** [Huluti/ImCompressor#2]
Hey, would be cool if in addition to flatpak, AppImages are provided.
They allow to start apolication by simple click to a single binary. More info https://appimage.org/

------------------------------
Edited by Huluti:
Possible packaging formats:
- [ ] AppImages
- [ ] Snaps
- [ ] Debs
- [ ] RPMs
- others?

Contributors: don't hesitate to post here to track progress.

**Comment by landswim** [comment]
+1

**Comment by Huluti** [comment]
I understand the need for some people. But I'm a developer not a packager. Help wanted here! I will appreciate any contribution. This issue can be used for listing the desired package formats (deb, appimage,...) and used to follow progress.

**Comment by gsantner** [comment]
As a developer you usually want people to use your stuff. So people somehow need to get the stuff.
As soon as you want people to get stuff = you have to care about packaging and formats.
Flatpak is one of them, some like flatpak/snap others do not. Having another option is never bad.

Just to note it, have my own image compress stuff and I wont use this one personally.
