### ISSUE TITLE
Feature Request: Compression indicator

### ISSUE THREAD

**Issue by trymeouteh** [Huluti/ImCompressor#20]
I set my PNG compression level to 7 since I want the max compression but it does take a long time. Please add a indicator next to the file letting the user know ImCompressor is compressing the image.

Maybe a percentage, meter, or a spinning indicator. When it is done I think a checkmark will be a nice indicator to let you know united 1.png compression is done.

**Comment by Huluti** [comment]
Sure! In my to-do list ;)

**Comment by Huluti** [comment]
Fixed in master. Will be in 0.7!
