### ISSUE TITLE
0.7 release 🎃

### ISSUE THREAD

**Issue by Huluti** [Huluti/ImCompressor#21]
HI! A new release will be out soon to fix #20 and going a little further.

### Added
- Add a spinner to indicate the progress of the compression.
- Using threads to compress images simultaneously.

### Changed
- Simplification of certain sentences.

### Fixed
- Really don't block the UI anymore when performing compression.

In order to have a good release I need some help of the translators to update their translations (very few changes) and ideally, it would be nice if some people test the new version from the source code to detect possible bugs.

**TODO before 0.7 release:**
- [x] update translations
    - [x] de :@Etamuk
    - [x] nl: @Vistaus
    - [ ] it: @albanobattistella
- [x] test the soft

Thank's in advance! 🎃

**Comment by Vistaus** [comment]
Done! :smile_cat:

**Comment by Etamuk** [comment]
@Huluti Thank you for the upcoming update.
German translation is also completed.

**Comment by Huluti** [comment]
0.7 released! Thank you!
