### ISSUE TITLE
Move Keep Metadata option to main menu

### ISSUE THREAD

**Issue by trymeouteh** [Huluti/ImCompressor#31]
I think that the "Keep Metadata" setting should on the main menu right under the loseless/lossy option and by default the keep metadata should be disabled. The reason for this is if you are compressing images that you want the metadata, and you have the new image no being saved as a new file, you will accidentally delete the metadata.

This way if you want to disable the metadata, you will need to enable it before you start compressing data just like you have to enable lossy compression before you begin compressing.

**Comment by Huluti** [comment]
The "keep metadata" option is already enabled by default.
I'll not moving this option in the main window to keep the UI as simple as possible and considering it's an advanced feature.
