### ISSUE TITLE
I can keep compressing an already compressed image

### ISSUE THREAD

**Issue by metmarkosaric** [Huluti/ImCompressor#33]
Thanks for the great app! 

I accidentally discovered that I can compress an already compressed image and get even further reduction in size. And I can keep doing that over and over again. See below for an example:

![Screenshot from 2020-05-07 12-02-48](https://user-images.githubusercontent.com/34340819/81309618-6baf7d80-9083-11ea-9805-bea8e17916cf.png)

Is this behaviour intentional or is there perhaps a way to get the maximum compression possible at once rather than having to repeat the process? Thanks again!

**Comment by Huluti** [comment]
Hi! Thanks for your return.
I have to say no and yes. It's the comportment of the libraries that I use. Should I avoid this or not, that is the question ? I want to say no.

You can set some options in the preferences to adjust the level compression. I'll think to add more maybe soon.

**Comment by metmarkosaric** [comment]
Thanks for the quick reply Hugo!

I think it's good to compress as much as it is possible to compress. I was just wondering if there a way to set it so it compresses an image to the maximum at once instead of having to compress the image over and over again manually? That would save time. 

The image in the screenshot above I compressed 10 times one after another and every time it was able to reduce the size further. Seems like it can go on and on so to automate that process somehow would be better.

**Comment by Huluti** [comment]
@metmarkosaric Hi!
Sorry to deal with this issue only now ... Could you tell me if you compress the image lossy or lossless? 
Thank you in advance!

**Comment by metmarkosaric** [comment]
No problem! I'm not sure if you did a fix but I haven't seen this behavior recently. I still use the app for all image optimization but these days I simply get a message that the best compression has already been used. So everything works all great. Thanks for a great app!

**Comment by Huluti** [comment]
I haven't made significant changes since May. Thank you for your answer ;) So I close this issue for now. If it happens again, don't hesitate to reopen it with the image used in copy.
