### ISSUE TITLE
[suggested to Add] A progress bar with the name of the file to be processed

### ISSUE THREAD

**Issue by Finoway** [Huluti/ImCompressor#36]
Hello,

I propose this to allow to know if we are compressing an image because it's showing nowhere (because when an image is long to compress we are not sure if it does or not or if it didn't crash)

**Comment by Huluti** [comment]
Hi!

Thank's for your suggestion. Currrently, there is a spinner to indicate that you're compressing an image. You don't see it?
I'll look at if a progress bar is a better solution.

**Comment by Finoway** [comment]
Hi, I had not seen, I select a lot of it at once and the freezer application sometimes so I didn't really understand...

Cordially Finoway,
