### ISSUE TITLE
[suggested to Add] Choose where to save + file name once compression is done

### ISSUE THREAD

**Issue by Finoway** [Huluti/ImCompressor#37]
Hello,

It might be nice to be able to choose where the compressed images will be saved and if there will be a suffix or not and/or be able to change the suffix in the file name.

**Comment by Huluti** [comment]
Hi! 
You can already choose if a suffix will be used and you can event change it in the preferences window.

![image](https://user-images.githubusercontent.com/5782198/96374260-ec65c000-1171-11eb-9bd6-5036f0c6e7a6.png)

I will not add an option to choose the folder as it would require a more complex user interface.
Thank's for your suggestions!

Please reopen if it doesn't answer your questions.
