### ISSUE TITLE
New HIG-compliant icon

### ISSUE THREAD

**Issue by bertob** [Huluti/ImCompressor#41]
Seeing as the app is already in Circle, it needs a new icon that conforms to the HIG as soon as possible (alongside the [new name](#39)).

Any preferences in terms of color/metaphor?

**Comment by Huluti** [comment]
I'll take a moment today to look at name suggestions and I'll give you some of my preferences for the logo. Thank's.

**Comment by Huluti** [comment]
For the icon what do you think of an image surrounded by a press a bit like on this image in the Gnome style?

![image](https://user-images.githubusercontent.com/5782198/101665560-68cb9f80-3a4d-11eb-900f-ae0f095b2ffd.png)

For the colors I don't have preferences.

**Comment by jimmac** [comment]
![Image_Compress](https://user-images.githubusercontent.com/14821/101675324-f44b2d80-3a59-11eb-832c-b825fe09fcd1.png)

While this communicates compression, it feels to go beyond lossy. It seems very destructive :) I would personally favor the other kind of metaphor that's used for compressed files and that's a zipper going around an image/video. I'll give that a stab.

**Comment by jimmac** [comment]
Yea, maybe not :)

![image](https://user-images.githubusercontent.com/14821/101696054-ca9fff80-3a75-11eb-8afe-e0921b42bccf.png)

**Comment by jannuary** [comment]
Here's Apple's Compressor, maybe that could be a useful metaphor:
![](https://i.imgur.com/qW3GkEZ.jpg) 
Another metaphor that comes to mind is a photo being folded, though not sure how that would work as an icon

**Comment by jimmac** [comment]
Might be a little too similar.

![image](https://user-images.githubusercontent.com/14821/101803189-8a418f80-3b10-11eb-8cd4-625fc7d3b821.png)

**Comment by Huluti** [comment]
@jimmac I like this last icon very much. It isn't exactly like the one jannuary has posted but it's true that it looks like it.
Maybe you can add several images in the press because the soft handle compression of several files at same time?

**Comment by jimmac** [comment]
Fullcolor rendition of the press concept. The symbolic is a little less clear, but it's a bit tricky given the constrains.

![image](https://user-images.githubusercontent.com/14821/101888095-03d38f00-3b9e-11eb-9f88-c73833fbf3cb.png)
