### ISSUE TITLE
Implement more compression options (lossy)

### ISSUE THREAD

**Issue by stiffler17** [Huluti/ImCompressor#6]
First of all congratulations on the great app.
Looks great!

But what I lack with all "simple, user-friendly" apps is that you can't adjust anything. I would like to use an app with which you can quickly and easily compress images.
With it it should be able to "lossless" as well as "lossy", if possible also the strength of the compression and so on.

take a look at the web interface of kraken.io, for example.
https://kraken.io/web-interface
I think this is a very good example that settings don't have to be complicated.

Too bad that this is only SASS.
Maybe I'll find some features of it in your app soon.

Please take this as honest constructive criticism.
Otherwise please continue like this. Kudos to you.

**Comment by Huluti** [comment]
Thank you very much for your feedback! Very appreciated. It is promised, I will study this possibility!

**Comment by stiffler17** [comment]
Wow, fast response :smile: 
Do you have paypal? I would donate something as motivation.

**Comment by Huluti** [comment]
Thank you very much for the support !! You can check the readme section of the project ;)

**Comment by Huluti** [comment]
![Capture d’écran du 2019-10-17 01-34-56](https://user-images.githubusercontent.com/5782198/66966678-5be83180-f07e-11e9-9dba-aded96635fc4.png)
@stiffler17 What do you think of such a design? I want to keep the soft as simple as possible.
Options will be in the preferences window.

**Comment by ripefig** [comment]
I think it needs a slider there too, low to high quality.

**Comment by Huluti** [comment]
@ripefig for now I think of something like this:
![Capture d’écran du 2019-10-17 16-11-41](https://user-images.githubusercontent.com/5782198/67016684-e0779600-f0f8-11e9-89a5-4b07fb966a57.png)

**Comment by ripefig** [comment]
Yeah, the main thing is that it works. But a slider in the main interface would be more in keeping with Gnome UI guidelines (and better UI in general).

**Comment by Huluti** [comment]
Fixed with 0.6!
